services:
  framepack_lllyasviel:
    build:
      context: .
      target: lllyasviel
    ports:
      - "8011:7860"
    volumes:
      - ./hf_download:/app/FramePack/hf_download
      - ./outputs:/app/FramePack/outputs
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    working_dir: /app/FramePack
    command: ["python", "/app/FramePack/demo_gradio.py", "--port", "7860", "--server", "0.0.0.0"]

  framepack_lllyasviel_f1:
    build:
      context: .
      target: lllyasviel
    ports:
      - "8012:7860"
    volumes:
      - ./hf_download:/app/FramePack/hf_download
      - ./outputs:/app/FramePack/outputs
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    working_dir: /app/FramePack
    command: ["python", "/app/FramePack/demo_gradio_f1.py", "--port", "7860", "--server", "0.0.0.0"]

  framepack_eichi:
    build:
      context: .
      target: eichi
    ports:
      - "8021:8001"
    volumes:
      - ./hf_download:/app/FramePack/webui/hf_download
      - ./outputs:/app/FramePack/webui/outputs
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    working_dir: /app/FramePack
    command: ["sh", "-c", "PYTHONPATH=/app/FramePack python /app/FramePack/webui/endframe_ichi.py --port 8001 --server 0.0.0.0"]

  framepack_eichi_f1:
    build:
      context: .
      target: eichi
    ports:
      - "8022:8001"
    volumes:
      - ./hf_download:/app/FramePack/webui/hf_download
      - ./outputs:/app/FramePack/webui/outputs
    deploy:
      resources:
        reservations:
          devices:
            - count: all
              capabilities: [gpu]
    working_dir: /app/FramePack
    command: ["sh", "-c", "PYTHONPATH=/app/FramePack python /app/FramePack/webui/endframe_ichi_f1.py --port 8001 --server 0.0.0.0"]
